### PR TITLE
do not check in vendor files

### PR DESCRIPTION
**Pull request by lewismarshall**

### CODE REVIEW

**Comment by jits** [comment]
In the default set up for generated Rails apps,  the `./vendor` directory is checked in to Git. The idea being that you can vendor certain external dependencies in here if needed (e.g. JS files that don't have an NPM etc. package).

Do you have something locally in this folder that needs to not be committed to the repo?

**Comment by lewismarshall** [comment]
> Do you have something locally in this folder that needs to not be committed to the repo?

Locally bundler created a folder:
```shell
$ ls vendor/bundle/ruby/2.5.0/
bin            build_info     bundler        cache          doc            extensions     gems           specifications
```

Maybe I should just add that alone to the ignore?

**Comment by jits** [comment]
@lewismarshall – ahh yes, some ways of using bundler do that (install to `vendor`) – makes sense to gitignore that specific folder (weirdly enough, it _should've_ have been in the gitignore – probably an oversight on my part).

**Comment by lewismarshall** [comment]
@jits no worries, forced pushed the more specific `/vendor/bundle` ignore

**Pull request merged**
